### ISSUE TITLE
Makerspace accessibility

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#116]
- Makerspaces don't do a good job of letting people know that differently abled people are welcome and we're happy to accommodate (comment from @rondauva during meeting, flesh out later)

**Comment by amandavisconti** [comment]
@kbdonnally Could you add a new section to /makerspace, maybe in the white space under "staffed hours"? I DM'd Ammon and Laura to see who should be contact person, but let's put Laura in for now. Text:

**Accessibility**
We happily provide accommodations so that everyone can reach our spaces and workshops, and use our equipment. Please email Laura Miller at <a href="mailto:lam2c@virginia.edu">email address</a>, or call the Scholars' Lab office at 434.243.8800 and ask to speak with her. We also have connections with colleagues at the other UVA campus makerspaces listed on the <a href="http://makergrounds.virginia.edu/">Makergrounds website</a>, and can put you in contact with a specific person if you'd like to discuss accommodations in those spaces.
