### ISSUE TITLE
Update colophon

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#16]
We'll need to update our Colophon as a result of this migration.

**Comment by amandavisconti** [comment]
Pushing temp text to /colophon page (basically "we need to provide a more detailed description in the future, but for now know this is jekyll, and here's the colophon for the previous site if you're interested"). Then moving this off the launch dealbreaker milestone.

**Comment by amandavisconti** [comment]
Since this is a Rainy Day issue, I'm removing the outdated colophon from the current site, and using the /about page to note who worked on the site renewal for now. The colophone text is below.
---
---
layout: page
title: Colophon
permalink: /colophon/
nav: false
---

We hope to update this page to reflect current and recent website work soon! In summary, we've migrated the site from WordPress to a Jekyll-generated static site.

Until we write a more detailed description of this site, you may be interested in the colophon information for the previous version of this website:

The Scholars' Lab site is written and maintained collaboratively by our staff, graduate fellows, and visiting scholars. We use an up-to-date version of [WordPress](http://wordpress.org) to run the site. Our site theme, Labnotes, is developed in-house and is tailored specifically for our needs, but the code is freely available in our [Github repository](http://github.com/scholarslab/labnotes). The development of the theme involves several tools:



	
  * We use the latest and greatest [HTML 5](http://en.wikipedia.org/wiki/HTML5) for page structure. Our HTML 5 template is a slightly modified version of [HTML5 Boilerplate](http://html5boilerplate.com/).

	
  * We use Cascading Style Sheets (CSS) for presentation. The CSS for this site was developed with a CSS pre-processor called [Sass](http://sass-lang.com/). We also use [Compass](http://compass-style.org/), a CSS authoring framework built on Sass, and [Susy](http://susy.oddbird.net/), a CSS grid framework also built on Sass.

	
  * We use several JavaScript libraries and frameworks, all of which are called from the [MaxCDN](http://www.maxcdn.com/) content delivery network:

	
    * [Modernizr](http://modernizr.com/) for browser feature detection;

	
    * [Respond.js](https://github.com/scottjehl/Respond) to help some older browsers use media queries for responsive design;

	
    * [Selectivizr](http://selectivizr.com/) to help older versions of Internet Explorer recognize CSS pseudo-classes and attribute selectors;

	
    * [Responsive Nav](http://responsive-nav.com/) to help make our main navigation responsive and mobile-friendly;

	
    * [Headroom](http://wicky.nillia.ms/headroom.js/) to help hide and show our site's header when scrolling.




	
  * The fonts used throughout the site are [Source Sans Pro](https://www.google.com/fonts/specimen/Source+Sans+Pro) and [Source Code Pro](https://www.google.com/fonts/specimen/Source+Code+Pro) from [Google Fonts](https://www.google.com/fonts).

	
  * Our background image is [Chalkboard](http://thepatternlibrary.com/#chalkboard) by Claudio Guglieri.

	
  * Most of our header images were taken by, and are copyright, [Shane Lin](/people/shane-lin/).


We also depend on a number of WordPress plugins, including:
[list_plugins]
