### ISSUE TITLE
Do we want categories and/or tags (if so, why/how)

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#270]
Old WP site had categories/tags, could search by either (also many posts had category name as part of URL structure). Possible tasks:

1. We could create individual redirects if desired (ugh)
2. We could create a new system of categories/tags that matches our current needs

**Comment by kbdonnally** [comment]
**On blog posts & events:** yes

**Why:** tag or category keywords are currently being used to generate eyebrow labels, which is how people scan lists of articles when they're reading them. We can certainly keep it to a limited vocabulary, but I think it's important that people are able to quickly scan what posts are about, since otherwise people are less likely to click through and read a given post. (Will link the article if want.)

**Comment by amandavisconti** [comment]
@kbdonnally I like the eyebrow labels (didn't know that term). Do these tags need to be updated on posts & events before release, or are they functioning okay enough with the current metadata for this to be done later?

**Comment by kbdonnally** [comment]
@amandavisconti They're working for now! Most of the recent blog posts don't have any tags/categories on them for some reason, so those display as "Miscellaneous", but everything has a label.

**Comment by amandavisconti** [comment]
Latest: tags and categories power eyebrow labels—cyan text right above post titles on /blog, and "filed" to + "tagged as" (which are currently commented out) on post.html template. May also power searching for fellow, grad research, praxis posts? But how do we want these to be used going forward?

**Comment by amandavisconti** [comment]
Dupe of #659
