### ISSUE TITLE
Fix blog footer bio images

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#353]
On http://maybe.scholarslab.org/2018/02/28/digital-humanities-dissertation-starter-kit/, currently two Amanda heads where truly one is enough. (Is from my updated avatar, so probably caused by my not following the same sizing as other bio pics and/or not creating a thumbnail version/storing correctly)

**Comment by jeremyboggs** [comment]
This is an issue because there are two files in `assets/img/people` with the string 'amanda-visconti' present in the file name. We should just remove one of those files.

We might update the logic on the posts layout, though, to check if a filename matching the author first-last exists in the static files array, instead of looping over all the static files on the site. 
But I think that's a rainy-day, maybe-never sort of optimization.

**Comment by walshbr** [comment]
PR I'm about to merge will close this. Deleted Amanda's extra image, made the logic a little tighter, and set the loop to break once it finds one image. So we shouldn't get extra images in the future. The more refined logic Jeremy is suggesting I can't get to work for the life of me. I'll close this for now since his suggestion is an optimization that isn't in the scope here but we can open a new ticket for that upgrade if you want.
