### ISSUE TITLE
Add more pedagogy/students chunks of work to "Our Work" page

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#374]
If and when suits your schedule. Can be an ongoing thing as you have time/new things to add. Thanks!

**Task:**
Either add them to the spreadsheet of SLab projects (SLab GDrive > Projects/Chunks of Work > SLab Projects List), or email Amanda a list and she'll add them

**Goals for "Our Work" page:**
1. Let people know what kinds of work we do, so they can come to us for questions about similar work they want to do or if they want to collaborate/build on our work (thus, inclusion of small projects, drafty stuff, personal R&D stuff in its early days...)
2. Showcase staff work & that we're doing a lot of stuff!
3. Advance our definition of scholarship: show how we include more than named projects or written research. Draft/early stage work, teaching, mentorship, librarianship, failed attempts, funny personal R&D things that taught you anything, a really small proof of concept

Some ideas for you to consider including:
1. Praxis Network Reboot
2. ILIADS sponsorship of student
3. Georgia Tech collaboration
4. W&L collaborations/regional grant proposals
5. All your personal R&D stuff, if you're comfortable with that (3D printing records, HILT teaching, writing/blogging/public speaking...)

**Comment by walshbr** [comment]
@amandavisconti - i've added some stuff to the bottom of the projects list in that drive folder. Rather than incorporate them into the master list it seemed like it might make most sense for you to have the additions at the bottom for you to add in if you think them correct? Let me know if this requires more work for the 'our work' section. Otherwise this can probably be closed.  #375 might be related as well.

**Comment by amandavisconti** [comment]
@walshbr Thank you! I'll close this and make a note in my issue to add these.
