### ISSUE TITLE
Template for new posts

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#38]
Show YAML options (e.g. categories and tags to choose from, how to format your author name, how to not break the site with colons in titles) and also include a few markdown pointers in the body of the template (how to format images with captions, how to link internally)

**Comment by walshbr** [comment]
Some of this is captured by a few rake tasks I put together when we were sprinting:

```
$ rake new_post["Title here", "First Last"]
```

Will produce a timestamped and dated template post in the posts folder that looks like this:

```
---
author: First Last
date: Current Date
layout: post
slug: title-here
title: Title Here
categories:
- Example category
---
```
Have one for making a new person and making a new research project too. They should definitely be improved, though, and they don't solve the problems of teaching markdown syntax.

**Comment by jeremyboggs** [comment]
@walshbr @amandavisconti Let's format the author as last-first, in a way that would match a CSV or `_data` representation of people, (e.g. a key in a YAML file). Would be easier to do some things with Jekyll and liquid if that's normalized. Same for projects.

**Comment by jeremyboggs** [comment]
Scratch that; Let's see about using the `slug` value for individual People records.

**Comment by walshbr** [comment]
Seems fine, but I think we should make some overarching decisions about the total metadata structure for efficiency's sake. Almost certain that the current format was chosen from decisions that we made during the sprint, which were themselves reformats of other decisions. Should get a structure we agree on so that we don't have to keep reprocessing the data. Not convinced we've thoroughly reviewed the metadata for the other categories either, even though #10 is closed. Might be worth reopening.

**Comment by jeremyboggs** [comment]
@walshbr Yes, there seem to be a handful of related issues, though their titles don't immediately indicate as much. Unless the group objects, I'd like to review these, and perhaps make a Project (or meta-issue) that collects these to help us focus.

**Comment by walshbr** [comment]
Go forth - reopen #10 or make a new issue.

**Comment by walshbr** [comment]
And fwiw - a lot of the work that remains to be done on the cleanup side can't happen until we finalize those decisions. Ie - @rondauva has cleaned up a bunch of stuff in the project files by hand, but, were we to reprocess them to capture changes to a metadata schema automatically, those sorts of changes would be lost. So that by-hand work has to wait until we get the other straight.

**Comment by jeremyboggs** [comment]
Created a project - https://github.com/scholarslab/scholarslab.org/projects/2

**Comment by jeremyboggs** [comment]
Creating a template for blog posts has already been done. If we have specific issues with the current template—based on on-going work with data and metadata—lets' open a new ticket that describes those specific issues in more detail. Closing this.
