### ISSUE TITLE
Accommodate Drafts

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#417]
As I see it we don't have a way to accommodate posts that are drafts - i.e. things that shouldn't show up in the main listing. Do we want such a thing?

**Comment by amandavisconti** [comment]
May depend on what @jeremyboggs and @mossiso decide—if we are going with hosting the production version on our own servers, might be best to not use drafts so that folks can both draft here on the dev version and see what it should look like when pushed to production? 

But it sounds like to get the site launched this fall, we might stay with GH Pages hosting—not sure if we'd use a separate repo with locked-down permissions for production, or would have folks draft in branches, or what

**Comment by walshbr** [comment]
That all sounds fine! There is a baked in way to accommodate post drafts in jekyll, but I'm not sure about the other types of things we have in collections. I think it makes sense to use some combination of branches and dev version.

**Comment by jeremyboggs** [comment]
@walshbr @amandavisconti Drafts should be topic branches off master. Would that work for now, until we come up with something more robust?

**Comment by walshbr** [comment]
Yeah that works.

**Comment by walshbr** [comment]
It might be worth integrating [Netlify](https://www.netlify.com/features/?gclid=CjwKCAjwuO3cBRAyEiwAzOxKsulBtwLizXmNwrUtSuHXFMLDeTf_OD2UtqclAdpkUxiTZ-W6STbPrhoCGI0QAvD_BwE) so that people can preview the parsed results of whatever they're working on in the pull request. Or including links to things like https://dillinger.io/ in the documentation. But I think this plan works for this issue - we can open others for those related ideas if we want.

**Comment by amandavisconti** [comment]
I'll add this to the documentation
