### ISSUE TITLE
Search Index Loading on Every Page

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#420]
@ZoeLeBlanc  - should the search_index and the corpus.json be loading on every page? I am not familiar with how that is set up to know the answer, but if not that could be a way to cut down load time a lot. Those files are pretty big and getting loaded on the people page, for example.
<img width="714" alt="screen shot 2018-08-16 at 2 58 04 pm" src="https://user-images.githubusercontent.com/2334220/44229061-e4123480-a164-11e8-8db4-7edfda6d1c34.png">

If that's expected we can close. If not, we should re-evaluate that.

**Comment by ZoeLeBlanc** [comment]
Good question @walshbr, it depends how we want to do the search. If it's from the navbar then likely yes, because the search is being loaded on every page. if search is only on it's own page, then we can just link the json files there. Happy to do a PR but have we decided on search functionality yet? I remember it being an issue awhile back but I never checked if things actually got built 😬

**Comment by amandavisconti** [comment]
@ZoeLeBlanc How difficult would it be to just link the JSON files from the search page, since we won't have a navbar search before the release (and possibly never)?
