### ISSUE TITLE
Make events page show events differently (current, future, then recent?)

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#428]
The Events page should show all events for a semester (past and future); currently, we only have events through the Bond Transcript-a-thon, so it isn't clear how events with dates in the future will be displayed? (Or, if we do have future events added, these aren't appearing. It's hard to tell because old event file names don't have uniform dates in the file name.)

**Comment by walshbr** [comment]
Both the /events page and the upcoming events bit just sort the dates with no real conception of what the current date is. So if we have things in the future, those would just rise to the top because they have the most recent date. I'm not sure there is a way to filter events based on upcoming / past, since this is a static site that only gets rebuilt when we push to it. I suppose we could work out some rough thing, maybe? But unless we work out a javascript solution I think we'd just be sort of roughly giving an estimate based on the last time the site was built as to a particular semester's content. Does that make sense? Happy to slack about it if not.

**Comment by walshbr** [comment]
Believe @jeremyboggs is going to be working on distributing events in the way that @lam2c requested. Going to unassign myself.

**Comment by amandavisconti** [comment]
Waiting on 2 updates suggested by Brandon in PR before closing this: https://github.com/scholarslab/scholarslab.org/pull/469
