### ISSUE TITLE
Consider student projects archive vs. /Work page

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#627]
We now have a separate /student-projects-archive page.

Do we want to:  
- [ ] Update individual project pages such that they cover everything the student-projects-archive items do (e.g. [recent] related blog posts)  
- [ ] Do we want to automatically pull new projects into this page if a student is listed as a project collaborator, or add some project metadata that will indicate if a project is student-led (and only pull those into the student archive page?)

Let's make sure these projects also show up on /work:
- [ ] Same as other projects, or highlight student work in a special section (or filter)?
- [ ] rather than having a standalone projects page, have this archive be a subsection of our work?
- [ ] see also #626

**Comment by walshbr** [comment]
To your questions @amandavisconti - 

1. I like the idea of adding related blog posts for each project! I'm not sure what kind overhead those calls are adding to the build time of the site each time we add one of them, but they seem negligible compared to how long the HTML link checker takes. 

2. I think we can add a metadata field to indicate a project is by a student. Shane's project is the only one that would cause issues, but I think we can classify it as a student project since he undertook work on it as a fellow.

3. I like the idea of taking the student projects archive page and making it a subsection on the bottom of the Our Work page.

**Comment by walshbr** [comment]
Seems like a fine way to filter these would be to use the research-category field. Could just add "Student" there when appropriate.
