### ISSUE TITLE
Review contents of /research/ and decide whether to reorganize &/or retitle

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#82]
## Issue
- Wasn't really sure what "research" implied, since research/scholarship is the whole theme of the Lab; this means the name is probably a little too ambiguous.

- We had talked about having a page for staff projects - as in, personal projects of any degree of formality - and we should address at next Monday's meeting (2/19) how that fits in with the content of this page.

- Also, I was under the impression that "Spatial Technologies" was getting its own page akin to that of the Makerspace page; so it seems like that information might not be best housed under this tab anymore.
 
### Possible steps to solve
- This page looks more akin to "technologies/software invented at the Scholars' Lab", which definitely is a worthwhile page to have. "Research" seems like something more unfinished than that.

- What might be a better title for this page, if we decide most of the content is ultimately cohesive?

**Comment by amandavisconti** [comment]
Projects? Scholarship? Work? Stuff/stuff we've made? This page is a catchall representing what we do—the easiest stuff to include is formal "projects" like Neatline and Praxis, but I'd also love for folks to post more of their small work here, e.g.:
- If Chris and Drew build a quick proof of concept to see if a faculty member's request is doable, can we treat that as scholarship by sharing it here so others can learn from or reuse?
- Our personal R&D projects, even if "all" we've done is thinking/planning. Both so folks outside the SLab hear about our interests, and to encourage us to treat these as seriously as other projects. E.g. I'd put an item for my pneumatic tube building

I worry that calling this "projects" make the stakes feel too high for folks to be posting drafty work or things at the idea stage—that's why we initially had separate "Research" and "Lab" pages, with "Lab" being for the more drafty experimental stuff.

We also need to think through the politics of how stuff on the page is organized—e.g. if we mark some projects as old/archived, would an external collaborator from that project fell bad?
