### ISSUE TITLE
Need text for Spatial Technologies section of homepage

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#96]
We've got sort of a "stream of consciousness" kinda thing going on right now, but it needs more information and language changes. Should be description blending GIS and AR/VR stuff; Amanda synthesizes this really well in the first sentence with "experts at thinking about space and time."

Also, the Makerspace section has hours - is this a thing for spatial tech stuff as well? (KBD will check the site for that info, but if it's not up there we should display on new site.)

**Comment by kbdonnally** [comment]
@rondauva and @lam2c - feel free to unassign selves from this! Figured a notification was the easiest way to make sure you saw this is all.

**Comment by amandavisconti** [comment]
I'm adding the info Spatial Tech emailed us

**Comment by amandavisconti** [comment]
I added the info Spatial Tech folks sent us, will PR in a moment.

This page still needs:
- [ ] Map/directions to spaces
- [ ] Info about Spatial Tech and why you'd want to contact them
- [ ] All filler text removed (by careful with this—Katherine grabbed old GIS text to use instead of Lorem Ipsum, so some stuff that looks correct is actually just filler)
