### ISSUE TITLE
Blog posts with HTML early in their text show raw HTML in the archive preview

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#996]
If a blog post has HTML or markdown very early in the text, that markup currently gets grabbed and thrown out on the listing of the most recent five posts on the blogroll. Ideally we'd probably just cut off the preview text early in those cases. Low priority, though, since it doesn't come up very often. 

<img width="898" alt="Screenshot 2024-07-01 at 9 24 18 AM" src="https://github.com/scholarslab/scholarslab.org/assets/2334220/58b47b8d-cfa0-4e6c-88f6-a51d85e5d347">

Tagging @amandavisconti so they can categorize it for the current workplan if necessary!

**Comment by amandavisconti** [comment]
I've fixed this and will push to slab and realignment branches

**Comment by amandavisconti** [comment]
I made some additional changes related to this, as my recent resin post still looked weird because the header was within the first 25 words:

- Removed pull-quote inclusion from post and blog pages, as zero content uses it. 
- Added optional post YAML inclusion of "summary: " to allow forcing a specific excerpt to appear on /blog (e.g. if header is in the first 25 words, making auto-generated excerpt look weird)
- Used summary YAML to make resin post excerpt read well
